name: Syncro API-docs

on:
  push:
    branches: [ "main" ]

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync data to prod
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_HOST_PORT }}
          script: |
            set -e
            cd ${{ secrets.SSH_PATH }}
            git pull
            npm install
            pm2 delete api-docs || true
            PORT=3569 pm2 start index.js --name api-docs
            pm2 save
